// fortawesome
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const partialSans = localFont({
  src: "./PartialSansKR-Regular.otf",
  variable: "--font-partial-sans",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${partialSans.variable} w-[1440px] overflow-auto antialiased`}
      >
        <div id="modal-root" />
        <Navbar />
        {modal}
        <main className="min-h-screen">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
